Added missing #endif to system_android.go
Since it does not compile currently:

../../../../go/pkg/mod/github.com/veandco/go-sdl2@v0.4.16/sdl/system_android.go:22:2: error: unterminated conditional directive
#if !(SDL_VERSION_ATLEAST(2,0,16))
 ^
1 error generated.