Added missing #endif to system_android.go (#511)
Since it does not compile currently:

../../../../go/pkg/mod/github.com/veandco/go-sdl2@v0.4.16/sdl/system_android.go:22:2: error: unterminated conditional directive
 ^
1 error generated.